# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: rubyschool.us # FIXME: configure to correct address when domain is ready
  secret_key_base: 34367c4f16ff339b9c3e0bb4dbc1c8b6d2de6746f40def75a17d07e72791355073f5c33c0041c7a25ba974ed461ca9e6e7c2b8ba05b364fc21254df022e91219
  email_provider_username: 60fc64c1-ff44-44a2-938a-33762f933a27
  email_provider_password: 60fc64c1-ff44-44a2-938a-33762f933a27

test:
  domain_name: example.com
  secret_key_base: 3b17b7e13fef9ff4baffd742ad3099b6485caa09b41eecd9ab491c5e67cc6029b9c49994bc54fbd6a00127ed42c3e62acd0eac96470e6d5e19a7c81e507d7d2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
